[build]
  publish = "."
  command = "# no build step"

[[redirects]]
  from = "/api/*"
  to = "https://nextmetro.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
